[package]
name = "lnaddrd"
version = "0.1.0"
edition = "2024"

[features]
default = []
postgres-import = ["dep:tokio-postgres"]

[dependencies]
anyhow = "1.0"
argon2 = "0.5"
axum = "0.7"
base64 = "0.22"
async-trait = "0.1"
clap = { version = "4.5", features = ["derive", "env"]}
diesel = { version = "2.2", features = ["sqlite", "r2d2"] }
diesel_migrations = "2.2.0"
hex = "0.4"
hkdf = "0.12"
hmac = "0.12"
idna = "1"
libsqlite3-sys = { version = "0.33", features = ["bundled"] }
lnurl-rs = { version = "0.9.0", default-features = false, features = [ "async-https-rustls" ] }
lightning-invoice = { version = "0.34.1", features = ["std"] }
maud = "0.27.0"
qrcode = { version = "0.14.1", features = ["svg"] }
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde = "1"
serde_json = "1.0.140"
sha2 = "0.10"
subtle = "2.6"
nostr-sdk = { version = "0.44", features = ["nip44"] }
tokio = { version = "1.36", features = ["full"] }
tempfile = "3"
tracing = "0.1"
tracing-subscriber = "0.3.19"
url = "2"
tokio-postgres = { version = "0.7", optional = true }
tower-http = { version = "0.6", features = ["cors"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
